"""Add nested subnets and additional fields

Revision ID: ee131273f642
Revises: c67d98c1cfda
Create Date: 2024-06-25 08:17:16.448504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee131273f642'
down_revision = 'c67d98c1cfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hostname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mac_address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rack', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('device', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('port', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_user', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_address', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('last_user')
        batch_op.drop_column('os')
        batch_op.drop_column('port')
        batch_op.drop_column('device')
        batch_op.drop_column('rack')
        batch_op.drop_column('mac_address')
        batch_op.drop_column('hostname')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
